language: generic

sudo: required
env:
  - DOCKER_VERSION=1.12.6
  - COMPOSE_VERSION=1.9.0
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

before_install:
  - curl -sSL https://get.docker.com/ | sh
  - sudo apt-get -y --force-yes install docker-engine=$DOCKER_VERSION-0~precise
  - sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-Linux-x86_64" \
    	&& sudo chmod +x /usr/local/bin/docker-compose

script:
  - ./gradlew test --info

after_failure:
  - sudo docker ps -a
  - sudo docker logs $(sudo docker ps -a -q -f name=_me_)

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test "$TRAVIS_TAG" != "" && test $TRAVIS_REPO_SLUG == "s4s0l/bootcker-gradle-plugin" && test $DOCKER_VERSION == "1.12.6" && ./gradlew bintrayUpload publishPlugins -Pversion="$TRAVIS_TAG" --info
